export class Child {
     ID              :number;
    LastName         :string;
    FirstName        :string;
    Gender           :string;
    Address          :string;
    BirthDate        :Date;
    ChildType        :string;
    // ID                      :number;
    // Child_Last_Name         :string;
    // Child_First_Name        :string;
    // Child_Gender            :string;
    // Child_Birth_Date        :string  ;
    // Child_Status            :number;
    // Child_Address           :string;
    // Child_Type              :number;
    // Parent1_Last_Name       :string;
    // Parent1_First_Name      :string;
    // Parent1_Private         :string;
    // Parent1_Gender          :string;
    // Parent1_Child_Relation  :string;
    // Parent1_Address         :string;
    // Parent1_Unit            :string;
    // Parent1_City            :string;
    // Parent1_Province        :string;
    // Parent1_Postal_Code     :string;
    // Parent1_Home_Phone      :string;
    // Parent1_Work_Phone      :string;
    // Parent1_Cell_Phone      :string;
    // Parent1_Email           :string;
    // Parent1_Primary_Email: boolean;
    // Parent1_Comments        :string;
    // Parent1_Special_Custody :string;
    // Parent2_Last_Name       :string;
    // Parent2_First_Name      :string;
    // Parent2_Private         :string;
    // Parent2_Gender          :string;
    // Parent2_Child_Relation  :string;
    // Parent2_Address         :string;
    // Parent2_Unit            :string;
    // Parent2_City            :string;
    // Parent2_Province        :string;
    // Parent2_Postal_Code     :string;
    // Parent2_Home_Phone      :string;
    // Parent2_Work_Phone      :string;
    // Parent2_Cell_Phone      :string;
    // Parent2_Email           :string;
    // Parent2_Primary_Email   :boolean;
    // Parent2_Comments        :string;
    // Parent2_Special_Custody :string;
    // Sibling_Name            :string;
    // Sibling_Age             :number;
    // Sibling_Gender          :string;
    // Contact1_Name           :string;
    // Contact1_Phone          :string;
    // Contact1_Email          :string;
    // Contact1_Address        :string;
    // Contact1_Relationship   :string;
    // Contact2_Name           :string;
    // Contact2_Phone          :string;
    // Contact2_Email          :string;
    // Contact2_Address        :string;
    // Contact2_Relationship   :string;
    // Contact3_Name           :string;
    // Contact3_Phone          :string;
    // Contact3_Email          :string;
    // Contact3_Address        :string;
    // Contact3_Relationship   :string;
    // Contact4_Name           :string;
    // Contact4_Phone          :string;
    // Contact4_Email          :string;
    // Contact4_Address        :string;
    //   Contact4_Relationship: string;
}
